### ISSUE TITLE
getFollowRequest isn't working more

### ISSUE THREAD

**Issue by rafhaelrc** [ErrorxCode/EasyInsta#4]
The method getFollowRequests isn't working. I tried to use it and the return always is 0. 
I verified in my personal account by instagram and i have some requests that the users haven't accept yet.

How i can solve it?

Thanks

**Comment by ErrorxCode** [comment]
Which request are you talking about ? It is for following request which
comes on private account. Have you tested on private account ?

Please first let me know and then I will proceed with this issue.

**Comment by rafhaelrc** [comment]
I'm talking about it : https://errorxcode.github.io/docs/easyinsta/com/xcoder/easyinsta/Instagram.html#getFollowRequests(com.xcoder.easyinsta.OnCompleteCallback)

This method should return a list that contains the names of the users that my account asked to follow and it didn't accept. Shouldn't it?

**Comment by rafhaelrc** [comment]
When i use this method, always the result is zero. The list always returns empty.

**Comment by ErrorxCode** [comment]
> This method should return a list that contains the names of the users that my account asked to follow and it didn't accept. Shouldn't it?

No. This method does not return the name of users "_that your account has asked to follow_", Instead, it returns the list of pending follow requests that **other has asked you to follow**.

It is clearly stated in the docs:
> Gets the pending follow requests. Empty list if none found but Never null.

These requests are those requests which are sent when we follow a private account. So here, it is returning an empty list because there are no follow requests on your account.
